### ISSUE TITLE
Mitigate phishing through arbitrary redirect value

### ISSUE THREAD

**Issue by m1212e** [DeutscheModelUnitedNations/munify-delegator#147]
Phishing is easy this way, we should add extra trust checks:

https://github.com/DeutscheModelUnitedNations/munify-delegator/blob/fa1578547faae6c384528714de02b1802523126c/src/routes/(authenticated)/my-account/%2Bpage.server.ts#L51

**Comment by ahsanfarooq210** [comment]
Hi @m1212e @Strehk . Please assign this issue to me, I want to work on this

**Comment by ahsanfarooq210** [comment]
Hi @m1212e.
is this what we were supposed to do?

```typescript

import { checkForError } from '$api/client';
import { loadApiHandler } from '$lib/helper/loadApiHandler';
import type { PageLoad } from './$types';

export const load: PageLoad = loadApiHandler(async ({ url, api, parent }) => {
	const { user } = await parent();
	let redirectUrl = url.searchParams.get('redirect');
	if (redirectUrl && new URL(redirectUrl).host !== url.host) {
		redirectUrl = null;
	}
	await api.auth['trigger-user-data-refresh'].post();
	const fullUser = await checkForError(api.user({ id: user.sub }).get());
	const { mySystemRoles } = await checkForError(api.auth['my-system-roles'].get());
	return {
		redirectUrl,
		fullUser,
		mySystemRoles,
		url
	};
});

```

**Comment by m1212e** [comment]
Yes, this looks close. I'd recommend setting the value to undefined where applicable.
Sorry for the delayed response!

**Comment by ahsanfarooq210** [comment]
Hi @m1212e. We now have to check if the redirect URL is of a trusted domain, can you give me a list of the trusted domains, or if we have that in the code, can you point it out for me

**Comment by m1212e** [comment]
I'd pull this info from the config or just look at the origin of the url from the request event parameter.

**Comment by ahsanfarooq210** [comment]
Hi @m1212e, Please review the PR
