### ISSUE TITLE
Add Favicons

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify-delegator#18]

**Comment by m1212e** [comment]
If you can specifically import those via an actual ESModule import you can put them in assets. This way vite can analyze and optimize them at build time. For things like libraries/wildcards this may not be applicable and you can put them in the static directory where they will be copied and made available at runtime.

**Comment by m1212e** [comment]
The favicon has a special place in vite projects. As far as I can remember you can put a favicon.ico in the static dir and it will be recognized. See the header section in the app.html for the config.

**Comment by TadeSF** [comment]
I previously used [this site](https://realfavicongenerator.net/) to generate all possibly needed icons for all platforms. I guess we are good to go if all of them just live in /static?
