### ISSUE TITLE
More generic breadcrumbs in layout components

### ISSUE THREAD

**Issue by m1212e** [DeutscheModelUnitedNations/munify-delegator#34]
We should check if there is a way to put the breadcrumbs in a more generic way into the layout components of the app

**Comment by TadeSF** [comment]
Checked it, but did not came up with a versatile and elegant solution. I figured this approach is a little bit more clean then having a component with monstrous if statements.
Please enlighten me if you find a better solution :D

**Comment by m1212e** [comment]
I see. Then this is probably the best approach. If theres some time left I'll have a look too, but for now your implementation is just fine!
