### ISSUE TITLE
Missing i18n Text

### ISSUE THREAD

**Issue by maximilianilzhoefer** [DeutscheModelUnitedNations/munify-delegator#50]
This Text should be i18n compatible
https://github.com/DeutscheModelUnitedNations/munify-delegator/blob/3d0e3adf637e6b33254966cbc304cf5695b948fa/src/api/routes/delegation.ts#L190

**Comment by maximilianilzhoefer** [comment]
There is another one in the same file:
https://github.com/DeutscheModelUnitedNations/munify-delegator/blob/3d0e3adf637e6b33254966cbc304cf5695b948fa/src/api/routes/delegation.ts#L250

**Comment by TadeSF** [comment]
Thanks! There are quite some Messages (especially warning etc.) not translated yet. @m1212e is it even possible to use i18n in the backend realm

**Comment by m1212e** [comment]
I made a PR ready which addresses this issue.

**Comment by m1212e** [comment]
@maximilianilzhoefer If you find any more hardcoded messages, let us know!
