### ISSUE TITLE
Investigate: Infinite Error Messages Loop on Safari

### ISSUE THREAD

**Issue by Strehk** [DeutscheModelUnitedNations/munify-delegator#63]
`TypeError: Argument 1 ('element') to Window.getComputedStyle must be an instance of Element`

See https://fb-delegator.dmun.de/posts/24/fehlermeldung-loop

**Comment by m1212e** [comment]
This should be fixed by removing the global error handler from the error toast component

**Comment by TadeSF** [comment]
Commented out for now

**Comment by Strehk** [comment]
@m1212e is this issue fixed by switching to the forms library?

**Comment by m1212e** [comment]
Yes I think this isn't an issue anymore
